# Задачи с сайта leetcode.com

In [1]:
import sqlite3

import pandas as pd

con = sqlite3.connect("sqlite.db")
cur = con.cursor()

In [2]:
def select(sql):
    return pd.read_sql(sql, con)


def crud(sql):
    cur.executescript(sql)
    con.commit()


def execute_formatted_sqlite(sql_schema):
    sql = ";\n".join(sql_schema.split("\n"))
    crud(sql)

### 175. Combine Two Tables (Easy)

Write a solution to report the first name, last name, city, and state of each person in the Person table. If the address of a personId is not present in the Address table, report null instead.

Return the result table in any order.

In [3]:
# SQLite3 не знает что такое TRUNCATE TABLE, поэтому нужно из запроса удалить эти команды.
# Добавить PRIMARY KEY к полям Id и OR REPLACE или IGNORE к INSERT, чтобы не дублировались строки
# при перезапуске. Или просто удалять таблици, если уже создана (DROP TABLE IF EXISTS table).

sql_schema = """
Drop table If Exists Person
Create table If Not Exists Person (personId int, firstName varchar(255), lastName varchar(255))
insert into Person (personId, lastName, firstName) values ('1', 'Wang', 'Allen')
insert into Person (personId, lastName, firstName) values ('2', 'Alice', 'Bob')
Drop table If Exists Address
Create table If Not Exists Address (addressId int, personId int, city varchar(255), state varchar(255))
insert into Address (addressId, personId, city, state) values ('1', '2', 'New York City', 'New York')
insert into Address (addressId, personId, city, state) values ('2', '3', 'Leetcode', 'California')
"""

# А так же после кажной строки поставить ';'
sql = ";\n".join(sql_schema.split("\n"))
print(sql)

# Так как несколько команд, нужен executescript(), а не execute()
cur.executescript(sql)

# В SQLite3 в Python нет автокомита (в CLI есть), поэтому:
con.commit()

;
Drop table If Exists Person;
Create table If Not Exists Person (personId int, firstName varchar(255), lastName varchar(255));
insert into Person (personId, lastName, firstName) values ('1', 'Wang', 'Allen');
insert into Person (personId, lastName, firstName) values ('2', 'Alice', 'Bob');
Drop table If Exists Address;
Create table If Not Exists Address (addressId int, personId int, city varchar(255), state varchar(255));
insert into Address (addressId, personId, city, state) values ('1', '2', 'New York City', 'New York');
insert into Address (addressId, personId, city, state) values ('2', '3', 'Leetcode', 'California');

In [4]:
sql = """--sql
SELECT
    p.firstName,
    p.lastName,
    a.city,
    a.state
FROM
    Person p
    LEFT JOIN Address a ON p.personId = a.personId;
"""
select(sql)

  firstName lastName           city     state
0     Allen     Wang           None      None
1       Bob    Alice  New York City  New York

### 176. Second Highest Salary (Med.)

Write a solution to find the second highest distinct salary from the Employee table. If there is no second highest salary, return null (return None in Pandas).

In [5]:
sql_schema = """
Drop table If Exists Employee
Create table If Not Exists Employee (id int, salary int)
insert into Employee (id, salary) values ('1', '100')
insert into Employee (id, salary) values ('2', '200')
insert into Employee (id, salary) values ('3', '300')
"""
execute_formatted_sqlite(sql_schema)

In [6]:
# Если в таблице всего одна зарплата, OFFSET 1 не находит строк — запрос не возвращает вообще ничего.
# Вложив запрос в SELECT (...) — он вернёт строку, даже если внутри ничего не найдено.

sql = """--sql
SELECT
    (
        SELECT DISTINCT
            e.salary
        FROM
            Employee e
        ORDER BY
            e.salary DESC
        LIMIT
            1 OFFSET 1
    ) AS SecondHighestSalary;
"""
select(sql)

   SecondHighestSalary
0                  200

### 177. Nth Highest Salary (Med.)

Write a solution to find the nth highest distinct salary from the Employee table. If there are less than n distinct salaries, return null.

In [7]:
sql_schema = """
Drop table If Exists Employee
Create table If Not Exists Employee (Id int, Salary int)
insert into Employee (id, salary) values ('1', '100')
insert into Employee (id, salary) values ('2', '200')
insert into Employee (id, salary) values ('3', '300')
"""
execute_formatted_sqlite(sql_schema)

In [8]:
# Для PostgreSQL
# CREATE
# OR REPLACE FUNCTION NthHighestSalary (n INT) RETURNS INT AS $$ -- начало тела функции
# SELECT
#     CASE
#         WHEN n < 1 THEN NULL
#         ELSE (
#             SELECT
#                 Salary
#             FROM
#                 (
#                     SELECT DISTINCT
#                         e.Salary
#                     FROM
#                         Employee e
#                     ORDER BY
#                         e.Salary DESC
#                     LIMIT
#                         1 OFFSET n -1
#                 ) AS result
#         )
#     END;

# $$ LANGUAGE SQL; -- конец тела функции с указанием используемого диалекта (чистый SQL)

# SELECT
#     NthHighestSalary (2);


# Имитация функции getNthHighestSalary для SQLite
def getNthHighestSalary(n):
    if n >= 1:
        sql = f"""--sql
        SELECT
            (
                SELECT DISTINCT
                    e.Salary
                FROM
                    Employee e
                ORDER BY
                    e.Salary desc
                LIMIT
                    1
                OFFSET
                    {n - 1}
            ) AS "getNthHighestSalary({n})";
        """
    else:
        sql = f"""--sql
        SELECT
            NULL AS "getNthHighestSalary({n})";
        """
    return select(sql)


getNthHighestSalary(-1)

  getNthHighestSalary(-1)
0                    None

### 178. Rank Scores (Med.)

Write a solution to find the rank of the scores. The ranking should be calculated according to the following rules:

The scores should be ranked from the highest to the lowest.
If there is a tie between two scores, both should have the same ranking.
After a tie, the next ranking number should be the next consecutive integer value. In other words, there should be no holes between ranks.
Return the result table ordered by score in descending order.

In [9]:
sql_schema = """
Drop table If Exists Scores
Create table If Not Exists Scores (id int, score DECIMAL(3,2))
insert into Scores (id, score) values ('1', '3.5')
insert into Scores (id, score) values ('2', '3.65')
insert into Scores (id, score) values ('3', '4.0')
insert into Scores (id, score) values ('4', '3.85')
insert into Scores (id, score) values ('5', '4.0')
insert into Scores (id, score) values ('6', '3.65')
"""
execute_formatted_sqlite(sql_schema)

In [10]:
sql = """--sql
SELECT
    s.score,
    DENSE_RANK() OVER (
        ORDER BY
            s.score DESC
    ) AS rank
FROM
    Scores s;
"""
select(sql)

   score  rank
0   4.00     1
1   4.00     1
2   3.85     2
3   3.65     3
4   3.65     3
5   3.50     4

### 180. Consecutive Numbers (Med.)

Find all numbers that appear at least three times consecutively.

In [11]:
sql_schema = """
Drop table If Exists Logs
Create table If Not Exists Logs (id int, num int)
insert into Logs (id, num) values ('1', '1')
insert into Logs (id, num) values ('2', '1')
insert into Logs (id, num) values ('3', '1')
insert into Logs (id, num) values ('4', '2')
insert into Logs (id, num) values ('5', '1')
insert into Logs (id, num) values ('6', '2')
insert into Logs (id, num) values ('7', '2')
"""
execute_formatted_sqlite(sql_schema)

In [12]:
sql = """--sql
SELECT DISTINCT
    t.num AS ConsecutiveNums
FROM
    (
        SELECT
            l.num,
            LAG(l.num, 1) OVER (
                ORDER BY
                    id
            ) AS prev_num,
            LAG(l.num, 2) OVER (
                ORDER BY
                    id
            ) AS sec_prev_num
        FROM
            Logs l
    ) t
WHERE
    t.num = t.prev_num
    AND t.num = t.sec_prev_num;
"""
select(sql)

   ConsecutiveNums
0                1

### 181. Employees Earning More Than Their Managers (Easy)

Write a solution to find the employees who earn more than their managers.

In [13]:
sql_schema = """
Drop table If Exists Employee
Create table If Not Exists Employee (id int, name varchar(255), salary int, managerId int)
insert into Employee (id, name, salary, managerId) values ('1', 'Joe', '70000', '3')
insert into Employee (id, name, salary, managerId) values ('2', 'Henry', '80000', '4')
insert into Employee (id, name, salary, managerId) values ('3', 'Sam', '60000', NULL)
insert into Employee (id, name, salary, managerId) values ('4', 'Max', '90000', NULL)
"""
execute_formatted_sqlite(sql_schema)

In [14]:
sql = """--sql
SELECT
    e.name AS Employee
FROM
    Employee e
WHERE
    e.salary > (
        SELECT
            m.salary
        FROM
            Employee m
        WHERE
            m.id = e.managerId
    );
"""
select(sql)

  Employee
0      Joe

### 182. Duplicate Emails (Easy)

Write a solution to report all the duplicate emails. Note that it's guaranteed that the email field is not NULL.

In [15]:
sql_schema = """
Drop table If Exists Person
Create table If Not Exists Person (id int, email varchar(255))
insert into Person (id, email) values ('1', 'a@b.com')
insert into Person (id, email) values ('2', 'c@d.com')
insert into Person (id, email) values ('3', 'a@b.com')
"""
execute_formatted_sqlite(sql_schema)

In [16]:
sql = """--sql
SELECT
    e.email AS Email
FROM
    (
        SELECT
            p.email,
            COUNT(p.email) dupl
        FROM
            Person p
        GROUP BY
            p.email
    ) e
WHERE
    e.dupl > 1;
"""
select(sql)

     Email
0  a@b.com

### 183. Customers Who Never Order (Easy)

Write a solution to find all customers who never order anything.

In [17]:
sql_schema = """
Drop table If Exists Customers
Create table If Not Exists Customers (id int, name varchar(255))
insert into Customers (id, name) values ('1', 'Joe')
insert into Customers (id, name) values ('2', 'Henry')
insert into Customers (id, name) values ('3', 'Sam')
insert into Customers (id, name) values ('4', 'Max')
Drop table If Exists Orders
Create table If Not Exists Orders (id int, customerId int)
insert into Orders (id, customerId) values ('1', '3')
insert into Orders (id, customerId) values ('2', '1')
"""
execute_formatted_sqlite(sql_schema)

In [18]:
sql = """--sql
SELECT
    c.name AS Customers
FROM
    Customers c
WHERE
    c.id NOT IN (
        SELECT
            o.customerId
        FROM
            Orders o
    );
"""
select(sql)

  Customers
0     Henry
1       Max

### 184. Department Highest Salary (Med.)

Write a solution to find employees who have the highest salary in each of the departments.

In [19]:
sql_schema = """
Drop table If Exists Employee
Create table If Not Exists Employee (id int, name varchar(255), salary int, departmentId int)
insert into Employee (id, name, salary, departmentId) values ('1', 'Joe', '70000', '1')
insert into Employee (id, name, salary, departmentId) values ('2', 'Jim', '90000', '1')
insert into Employee (id, name, salary, departmentId) values ('3', 'Henry', '80000', '2')
insert into Employee (id, name, salary, departmentId) values ('4', 'Sam', '60000', '2')
insert into Employee (id, name, salary, departmentId) values ('5', 'Max', '90000', '1')
Drop table If Exists Department
Create table If Not Exists Department (id int, name varchar(255))
insert into Department (id, name) values ('1', 'IT')
insert into Department (id, name) values ('2', 'Sales')
"""
execute_formatted_sqlite(sql_schema)

In [20]:
sql = """--sql
SELECT
    d.name AS Department,
    e.name AS Employee,
    e.salary AS Salary
FROM
    (
        SELECT
            e.*,
            DENSE_RANK() OVER (
                PARTITION BY
                    e.departmentId
                ORDER BY
                    e.salary DESC
            ) AS rank
        FROM
            Employee e
    ) e
    LEFT JOIN Department d ON e.departmentId = d.id
WHERE
    e.rank = 1
ORDER BY
    d.name,
    e.name;
"""
select(sql)

  Department Employee  Salary
0         IT      Jim   90000
1         IT      Max   90000
2      Sales    Henry   80000

### 185. Department Top Three Salaries (Hard)

A company's executives are interested in seeing who earns the most money in each of the company's departments. A high earner in a department is an employee who has a salary in the top three unique salaries for that department.

Write a solution to find the employees who are high earners in each of the departments.

In [21]:
sql_schema = """
Drop table If Exists Employee
Create table If Not Exists Employee (id int, name varchar(255), salary int, departmentId int)
insert into Employee (id, name, salary, departmentId) values ('1', 'Joe', '85000', '1')
insert into Employee (id, name, salary, departmentId) values ('2', 'Henry', '80000', '2')
insert into Employee (id, name, salary, departmentId) values ('3', 'Sam', '60000', '2')
insert into Employee (id, name, salary, departmentId) values ('4', 'Max', '90000', '1')
insert into Employee (id, name, salary, departmentId) values ('5', 'Janet', '69000', '1')
insert into Employee (id, name, salary, departmentId) values ('6', 'Randy', '85000', '1')
insert into Employee (id, name, salary, departmentId) values ('7', 'Will', '70000', '1')
Drop table If Exists Department
Create table If Not Exists Department (id int, name varchar(255))
insert into Department (id, name) values ('1', 'IT')
insert into Department (id, name) values ('2', 'Sales')
"""
execute_formatted_sqlite(sql_schema)

In [22]:
sql = """--sql
SELECT
    d.name AS Department,
    e.name AS Employee,
    e.salary AS Salary
FROM
    (
        SELECT
            e.*,
            DENSE_RANK() OVER (
                PARTITION BY
                    e.departmentId
                ORDER BY
                    e.salary DESC
            ) AS rank
        FROM
            Employee e
    ) e
    LEFT JOIN Department d ON e.departmentId = d.id
WHERE
    e.rank <= 3
ORDER BY
    d.name,
    e.salary DESC;
"""
select(sql)

  Department Employee  Salary
0         IT      Max   90000
1         IT      Joe   85000
2         IT    Randy   85000
3         IT     Will   70000
4      Sales    Henry   80000
5      Sales      Sam   60000

### 196. Delete Duplicate Emails (Easy)

Write a solution to delete all duplicate emails, keeping only one unique email with the smallest id.

For SQL users, please note that you are supposed to write a DELETE statement and not a SELECT one.

For Pandas users, please note that you are supposed to modify Person in place.

After running your script, the answer shown is the Person table. The driver will first compile and run your piece of code and then show the Person table. The final order of the Person does not matter.

In [23]:
sql_schema = """
Drop table If Exists Person
Create table If Not Exists Person (Id int, Email varchar(255))
insert into Person (id, email) values ('1', 'john@example.com')
insert into Person (id, email) values ('2', 'bob@example.com')
insert into Person (id, email) values ('3', 'john@example.com')
"""
execute_formatted_sqlite(sql_schema)

In [24]:
sql = """--sql
DELETE
FROM
    Person
WHERE
    id NOT IN (
        SELECT
            MIN(p.id)
        FROM
            Person p
        GROUP BY
            p.email
    );
"""
crud(sql)

### 197. Rising Temperature (Easy)

Write a solution to find all dates' id with higher temperatures compared to its previous dates (yesterday).

In [25]:
sql_schema = """
Drop table If Exists Weather
Create table If Not Exists Weather (id int, recordDate date, temperature int)
insert into Weather (id, recordDate, temperature) values ('1', '2015-01-01', '10')
insert into Weather (id, recordDate, temperature) values ('2', '2015-01-02', '25')
insert into Weather (id, recordDate, temperature) values ('3', '2015-01-03', '20')
insert into Weather (id, recordDate, temperature) values ('4', '2015-01-04', '30')
"""
execute_formatted_sqlite(sql_schema)

In [26]:
# Для PostgreSL `ON w1.recordDate = w2.recordDate + INTERVAL '1 day'`
# Для MySQL `ON w1.recordDate = DATE_ADD(w2.recordDate, INTERVAL 1 DAY)'`
sql = """--sql
SELECT
    w1.id
FROM
    Weather w1
    INNER JOIN Weather w2 ON w1.recordDate = DATE(w2.recordDate, '+1 day')
WHERE
    w1.temperature > w2.temperature
ORDER BY
    w1.id;
"""
select(sql)

   id
0   2
1   4

### 262. Trips and Users (Hard)

The cancellation rate is computed by dividing the number of canceled (by client or driver) requests with unbanned users by the total number of requests with unbanned users on that day.

Write a solution to find the cancellation rate of requests with unbanned users (both client and driver must not be banned) each day between "2013-10-01" and "2013-10-03" with at least one trip. Round Cancellation Rate to two decimal points.

In [27]:
# ENUM - перечислимый тип фиксированным списком СТРОКОВЫХ значений хранящихся внутри схемы БД.
# SQLite не поддерживает ENUM, но можно сделать ограничение через CHECK.
# ENUM('completed', 'cancelled_by_driver', 'cancelled_by_client') заменить на TEXT вместе с CHECK:
# TEXT CHECK(status IN ('completed', 'cancelled_by_driver', 'cancelled_by_client'))
sql_schema = """
Drop table If Exists Trips
Create table If Not Exists Trips (id int, client_id int, driver_id int, city_id int, status text CHECK(status In ('completed', 'cancelled_by_driver', 'cancelled_by_client')), request_at varchar(50))
insert into Trips (id, client_id, driver_id, city_id, status, request_at) values ('1', '1', '10', '1', 'completed', '2013-10-01')
insert into Trips (id, client_id, driver_id, city_id, status, request_at) values ('2', '2', '11', '1', 'cancelled_by_driver', '2013-10-01')
insert into Trips (id, client_id, driver_id, city_id, status, request_at) values ('3', '3', '12', '6', 'completed', '2013-10-01')
insert into Trips (id, client_id, driver_id, city_id, status, request_at) values ('4', '4', '13', '6', 'cancelled_by_client', '2013-10-01')
insert into Trips (id, client_id, driver_id, city_id, status, request_at) values ('5', '1', '10', '1', 'completed', '2013-10-02')
insert into Trips (id, client_id, driver_id, city_id, status, request_at) values ('6', '2', '11', '6', 'completed', '2013-10-02')
insert into Trips (id, client_id, driver_id, city_id, status, request_at) values ('7', '3', '12', '6', 'completed', '2013-10-02')
insert into Trips (id, client_id, driver_id, city_id, status, request_at) values ('8', '2', '12', '12', 'completed', '2013-10-03')
insert into Trips (id, client_id, driver_id, city_id, status, request_at) values ('9', '3', '10', '12', 'completed', '2013-10-03')
insert into Trips (id, client_id, driver_id, city_id, status, request_at) values ('10', '4', '13', '12', 'cancelled_by_driver', '2013-10-03')
Drop table If Exists Users
Create table If Not Exists Users (users_id int, banned varchar(50), role text CHECK(role In ('client', 'driver', 'partner')))
insert into Users (users_id, banned, role) values ('1', 'No', 'client')
insert into Users (users_id, banned, role) values ('2', 'Yes', 'client')
insert into Users (users_id, banned, role) values ('3', 'No', 'client')
insert into Users (users_id, banned, role) values ('4', 'No', 'client')
insert into Users (users_id, banned, role) values ('10', 'No', 'driver')
insert into Users (users_id, banned, role) values ('11', 'No', 'driver')
insert into Users (users_id, banned, role) values ('12', 'No', 'driver')
insert into Users (users_id, banned, role) values ('13', 'No', 'driver')
"""
execute_formatted_sqlite(sql_schema)

In [28]:
# в SQLite 0 / 2 = 0, а 1 / 2 = 0, если оба аргумента — INTEGER. Поэтому явно бодавляем * 1.0.
# P.S. Одинарные кавычки (') нельзя использовать для именования столбцов — они интерпретируются как
# строковые литералы. Для совместимости с другими СУБД использовать двойные (").
# В PostgreSQL нельзя напрямую применять SUM(...) к BOOLEAN - нужно использовать CASE WHEN. А также
# полноценный подзапрос вместо NOT IN bloked_user.
sql = """--sql
WITH
    blocked_user AS (
        SELECT
            u.users_id
        FROM
            Users u
        WHERE
            u.banned = 'Yes'
    )
SELECT
    t.request_at AS Day,
    ROUND(SUM(t.status != 'completed') * 1.0 / COUNT(*), 2) AS "Cancellation Rate"
FROM
    Trips t
WHERE
    t.client_id NOT IN blocked_user
    AND t.driver_id NOT IN blocked_user
    AND t.request_at BETWEEN '2013-10-01' AND '2013-10-03'
GROUP BY
    t.request_at
ORDER BY
    Day;
"""
select(sql)

          Day  Cancellation Rate
0  2013-10-01               0.33
1  2013-10-02               0.00
2  2013-10-03               0.50

### 511. Game Play Analysis I (Easy)

Write a solution to find the first login date for each player.

In [29]:
sql_schema = """
Drop table If Exists Activity
Create table If Not Exists Activity (player_id int, device_id int, event_date date, games_played int)
insert into Activity (player_id, device_id, event_date, games_played) values ('1', '2', '2016-03-01', '5')
insert into Activity (player_id, device_id, event_date, games_played) values ('1', '2', '2016-05-02', '6')
insert into Activity (player_id, device_id, event_date, games_played) values ('2', '3', '2017-06-25', '1')
insert into Activity (player_id, device_id, event_date, games_played) values ('3', '1', '2016-03-02', '0')
insert into Activity (player_id, device_id, event_date, games_played) values ('3', '4', '2018-07-03', '5')
"""
execute_formatted_sqlite(sql_schema)

In [30]:
sql = """--sql
SELECT
    a.player_id,
    MIN(a.event_date) as first_login
FROM
    Activity a
GROUP BY
    a.player_id;
"""
select(sql)

   player_id first_login
0          1  2016-03-01
1          2  2017-06-25
2          3  2016-03-02

### 550. Game Play Analysis IV (Med.)

Write a solution to report the fraction of players that logged in again on the day after the day they first logged in, rounded to 2 decimal places. In other words, you need to determine the number of players who logged in on the day immediately following their initial login, and divide it by the number of total players.

In [31]:
sql_schema = """
Drop table If Exists Activity
Create table If Not Exists Activity (player_id int, device_id int, event_date date, games_played int)
insert into Activity (player_id, device_id, event_date, games_played) values ('1', '2', '2016-03-01', '5')
insert into Activity (player_id, device_id, event_date, games_played) values ('1', '2', '2016-03-02', '6')
insert into Activity (player_id, device_id, event_date, games_played) values ('2', '3', '2017-06-25', '1')
insert into Activity (player_id, device_id, event_date, games_played) values ('3', '1', '2016-03-02', '0')
insert into Activity (player_id, device_id, event_date, games_played) values ('3', '4', '2018-07-03', '5')
"""
execute_formatted_sqlite(sql_schema)

In [32]:
# В PostgreSQL: a.event_date - INTERVAL '1 day'
# Вместо CAST(COUNT(r.player_id) AS real) можно просто * 1.0
sql = """--sql
WITH
    first_login AS (
        SELECT
            a.player_id,
            MIN(a.event_date) AS first_login
        FROM
            Activity a
        GROUP BY
            a.player_id
    ),
    reentry_next_day AS (
        SELECT
            f.*,
            CASE
                WHEN a.event_date IS NOT NULL THEN 1
                ELSE 0
            END AS reentry_login
        FROM
            first_login f
            LEFT JOIN Activity a ON f.player_id = a.player_id
            AND f.first_login = DATE(a.event_date, '-1 day')
    )
SELECT
    ROUND(
        1.0 * SUM(r.reentry_login) / COUNT(r.player_id),
        2
    ) AS fraction
FROM
    reentry_next_day r;
"""
select(sql)

   fraction
0      0.33

### 570. Managers with at Least 5 Direct Reports (Med.)

Write a solution to find managers with at least five direct reports.

In [33]:
sql_schema = """
Drop table If Exists Employee
Create table If Not Exists Employee (id int, name varchar(255), department varchar(255), managerId int)
insert into Employee (id, name, department, managerId) values ('101', 'John', 'A', NULL)
insert into Employee (id, name, department, managerId) values ('102', 'Dan', 'A', '101')
insert into Employee (id, name, department, managerId) values ('103', 'James', 'A', '101')
insert into Employee (id, name, department, managerId) values ('104', 'Amy', 'A', '101')
insert into Employee (id, name, department, managerId) values ('105', 'Anne', 'A', '101')
insert into Employee (id, name, department, managerId) values ('106', 'Ron', 'B', '101')
"""
execute_formatted_sqlite(sql_schema)

In [34]:
# Вариант с JOIN работае быстрее чем с WHERE (WHERE e.id in (SELECT ...), т.к. SQL-оптимизатор ряда
# СУБД преобразует его в EXISTS или JOIN). COUNT(e.managerId) можно вынести из SELTCT в HAVING и тогда
# в SELECT оставить только e.managerId (сразу готовый список id-шников без дополнительного подзапроса).
sql = """--sql
SELECT
    e.name
FROM
    Employee e
    INNER JOIN (
        SELECT
            e.managerId
        FROM
            Employee e
        GROUP BY
            e.managerId
        HAVING
            COUNT(e.managerId) >= 5
    ) m ON e.id = m.managerId;
"""
select(sql)

   name
0  John

### 577. Employee Bonus (Easy)

Write a solution to report the name and bonus amount of each employee with a bonus less than 1000.

In [35]:
sql_schema = """
Drop table If Exists Employee
Create table If Not Exists Employee (empId int, name varchar(255), supervisor int, salary int)
insert into Employee (empId, name, supervisor, salary) values ('3', 'Brad', NULL, '4000')
insert into Employee (empId, name, supervisor, salary) values ('1', 'John', '3', '1000')
insert into Employee (empId, name, supervisor, salary) values ('2', 'Dan', '3', '2000')
insert into Employee (empId, name, supervisor, salary) values ('4', 'Thomas', '3', '4000')
Drop table If Exists Bonus
Create table If Not Exists Bonus (empId int, bonus int)
insert into Bonus (empId, bonus) values ('2', '500')
insert into Bonus (empId, bonus) values ('4', '2000')
"""
execute_formatted_sqlite(sql_schema)

In [36]:
# Подразумевается что если сотрудник без бонуса - его бонус равен 0. Поэтому эти сотрудники включены в результат.
# Т.е. сотрудники WHERE COALESCE(b.bonus, 0) < 1000.
sql = """--sql
SELECT
    e.name,
    b.bonus
FROM
    Employee e
    LEFT JOIN Bonus b ON e.empId = b.empId
WHERE
    b.bonus < 1000
    OR b.bonus IS NULL
ORDER BY
    b.bonus,
    e.name;
"""
select(sql)

   name  bonus
0  Brad    NaN
1  John    NaN
2   Dan  500.0

### 584. Find Customer Referee (Easy)

Find the names of the customer that are either:

1. referred by any customer with id != 2.
2. not referred by any customer.

In [37]:
sql_schema = """
Drop table If Exists Customer
Create table If Not Exists Customer (id int, name varchar(25), referee_id int)
insert into Customer (id, name, referee_id) values ('1', 'Will', NULL)
insert into Customer (id, name, referee_id) values ('2', 'Jane', NULL)
insert into Customer (id, name, referee_id) values ('3', 'Alex', '2')
insert into Customer (id, name, referee_id) values ('4', 'Bill', NULL)
insert into Customer (id, name, referee_id) values ('5', 'Zack', '1')
insert into Customer (id, name, referee_id) values ('6', 'Mark', '2')
"""
execute_formatted_sqlite(sql_schema)

In [38]:
sql = """--sql
SELECT
    c.name
FROM
    Customer c
WHERE
    c.referee_id != 2
    OR c.referee_id IS NULL
ORDER BY
    c.name;
"""
select(sql)

   name
0  Bill
1  Jane
2  Will
3  Zack

### 585. Investments in 2016 (Med.)

Write a solution to report the sum of all total investment values in 2016 tiv_2016, for all policyholders who:

- have the same tiv_2015 value as one or more other policyholders, and
- are not located in the same city as any other policyholder (i.e., the (lat, lon) attribute pairs must be unique).

Round tiv_2016 to two decimal places.

In [39]:
sql_schema = """
Drop table If Exists Insurance
Create Table If Not Exists Insurance (pid int, tiv_2015 float, tiv_2016 float, lat float, lon float)
insert into Insurance (pid, tiv_2015, tiv_2016, lat, lon) values ('1', '10', '5', '10', '10')
insert into Insurance (pid, tiv_2015, tiv_2016, lat, lon) values ('2', '20', '20', '20', '20')
insert into Insurance (pid, tiv_2015, tiv_2016, lat, lon) values ('3', '10', '30', '20', '20')
insert into Insurance (pid, tiv_2015, tiv_2016, lat, lon) values ('4', '10', '40', '40', '40')
"""
execute_formatted_sqlite(sql_schema)

In [40]:
# И опять же в PostgreSQL нужно было бы tiv_2016 привести к numeric, т.к. по умолчанию SUM() возращает
# результат в double precision, а ROUND() работает только с numeric: ROUND(SUM(i.tiv_2016)::numeric, 2).
# JOIN работает быстрее IN, поэтому лучше использовать его вместо WHERE с поиском по IN.
# INNER join - логический аналог WHERE ... IN.
sql = """--sql
SELECT
    ROUND(SUM(i.tiv_2016), 2) AS tiv_2016
FROM
    Insurance i
    INNER JOIN (
        SELECT
            tiv_2015
        FROM
            Insurance
        GROUP BY
            tiv_2015
        HAVING
            COUNT(*) > 1
    ) i1 ON i.tiv_2015 = i1.tiv_2015
    INNER JOIN (
        SELECT
            i2.lat,
            i2.lon
        FROM
            Insurance i2
        GROUP BY
            i2.lat,
            i2.lon
        HAVING
            COUNT(*) = 1
    ) i2 ON i.lat = i2.lat
    AND i.lon = i2.lon;
"""
select(sql)

   tiv_2016
0      45.0

### 586. Customer Placing the Largest Number of Orders (Easy)

Write a solution to find the customer_number for the customer who has placed the largest number of orders.

The test cases are generated so that exactly one customer will have placed more orders than any other customer.

In [41]:
sql_schema = """
Drop table If Exists orders
Create table If Not Exists orders (order_number int, customer_number int)
insert into orders (order_number, customer_number) values ('1', '1')
insert into orders (order_number, customer_number) values ('2', '2')
insert into orders (order_number, customer_number) values ('3', '3')
insert into orders (order_number, customer_number) values ('4', '3')
"""
execute_formatted_sqlite(sql_schema)

In [42]:
sql = """--sql
SELECT
    o.customer_number
FROM
    orders o
GROUP BY
    o.customer_number
ORDER BY
    COUNT(o.order_number) DESC
LIMIT
    1;
"""
select(sql)

   customer_number
0                3

### 595. Big Countries (Easy)

A country is big if:

- it has an area of at least three million (i.e., 3000000 km2), or
- it has a population of at least twenty-five million (i.e., 25000000).

Write a solution to find the name, population, and area of the big countries.

In [43]:
sql_schema = """
Drop table If Exists World
Create table If Not Exists World (name varchar(255), continent varchar(255), area int, population int, gdp bigint)
insert into World (name, continent, area, population, gdp) values ('Afghanistan', 'Asia', '652230', '25500100', '20343000000')
insert into World (name, continent, area, population, gdp) values ('Albania', 'Europe', '28748', '2831741', '12960000000')
insert into World (name, continent, area, population, gdp) values ('Algeria', 'Africa', '2381741', '37100000', '188681000000')
insert into World (name, continent, area, population, gdp) values ('Andorra', 'Europe', '468', '78115', '3712000000')
insert into World (name, continent, area, population, gdp) values ('Angola', 'Africa', '1246700', '20609294', '100990000000')
"""
execute_formatted_sqlite(sql_schema)

In [44]:
sql = """--sql
SELECT
    w.name,
    w.population,
    w.area
FROM
    World w
WHERE
    w.area >= 3000000
    OR w.population >= 25000000
ORDER BY
    w.name;
"""
select(sql)

          name  population     area
0  Afghanistan    25500100   652230
1      Algeria    37100000  2381741

### 596. Classes With at Least 5 Students (Easy)

Write a solution to find all the classes that have at least five students.

In [45]:
sql_schema = """
Drop table If Exists Courses
Create table If Not Exists Courses (student varchar(255), class varchar(255))
insert into Courses (student, class) values ('A', 'Math')
insert into Courses (student, class) values ('B', 'English')
insert into Courses (student, class) values ('C', 'Math')
insert into Courses (student, class) values ('D', 'Biology')
insert into Courses (student, class) values ('E', 'Math')
insert into Courses (student, class) values ('F', 'Computer')
insert into Courses (student, class) values ('G', 'Math')
insert into Courses (student, class) values ('H', 'Math')
insert into Courses (student, class) values ('I', 'Math')
"""
execute_formatted_sqlite(sql_schema)

In [46]:
sql = """--sql
SELECT
    c.class
FROM
    Courses c
GROUP BY
    c.class
HAVING
    COUNT(*) >= 5
ORDER BY
    c.class;
"""
select(sql)

  class
0  Math

### 601. Human Traffic of Stadium (Hard)

Write a solution to display the records with three or more rows with consecutive id's, and the number of people is greater than or equal to 100 for each.

Return the result table ordered by visit_date in ascending order.

In [47]:
sql_schema = """
Drop table If Exists Stadium
Create table If Not Exists Stadium (id int, visit_date DATE NULL, people int)
insert into Stadium (id, visit_date, people) values ('1', '2017-01-01', '10')
insert into Stadium (id, visit_date, people) values ('2', '2017-01-02', '109')
insert into Stadium (id, visit_date, people) values ('3', '2017-01-03', '150')
insert into Stadium (id, visit_date, people) values ('4', '2017-01-04', '99')
insert into Stadium (id, visit_date, people) values ('5', '2017-01-05', '145')
insert into Stadium (id, visit_date, people) values ('6', '2017-01-06', '1455')
insert into Stadium (id, visit_date, people) values ('7', '2017-01-07', '199')
insert into Stadium (id, visit_date, people) values ('8', '2017-01-09', '188')
"""
execute_formatted_sqlite(sql_schema)

In [48]:
sql = """--sql
WITH
    stadium_rank AS (
        SELECT
            s.*,
            s.id - ROW_NUMBER() OVER (
                ORDER BY
                    s.id
            ) AS rnk
        FROM
            Stadium s
        WHERE
            s.people >= 100
    )
SELECT
    sr.id,
    sr.visit_date,
    sr.people
FROM
    stadium_rank sr
WHERE
    sr.rnk IN (
        SELECT
            rnk
        FROM
            stadium_rank
        GROUP BY
            rnk
        HAVING
            COUNT(*) >= 3
    )
ORDER BY
    sr.visit_date;
"""
select(sql)

   id  visit_date  people
0   5  2017-01-05     145
1   6  2017-01-06    1455
2   7  2017-01-07     199
3   8  2017-01-09     188

### 602. Friend Requests II: Who Has the Most Friends (Med.)

Write a solution to find the people who have the most friends and the most friends number.

The test cases are generated so that only one person has the most friends.

In [49]:
sql_schema = """
Drop table If Exists RequestAccepted
Create table If Not Exists RequestAccepted (requester_id int not null, accepter_id int null, accept_date date null)
insert into RequestAccepted (requester_id, accepter_id, accept_date) values ('1', '2', '2016/06/03')
insert into RequestAccepted (requester_id, accepter_id, accept_date) values ('1', '3', '2016/06/08')
insert into RequestAccepted (requester_id, accepter_id, accept_date) values ('2', '3', '2016/06/08')
insert into RequestAccepted (requester_id, accepter_id, accept_date) values ('3', '4', '2016/06/09')
"""
execute_formatted_sqlite(sql_schema)

In [50]:
sql = """--sql
SELECT
    u.id,
    COUNT(*) AS num
FROM
    (
        SELECT
            r.requester_id AS id
        FROM
            RequestAccepted r
        UNION ALL
        SELECT
            r.accepter_id AS id
        FROM
            RequestAccepted r
    ) u
GROUP BY
    u.id
ORDER BY
    num DESC
LIMIT
    1;
"""
select(sql)

   id  num
0   3    3

### 607. Sales Person (Easy)

Write a solution to find the names of all the salespersons who did not have any orders related to the company with the name "RED".

In [51]:
sql_schema = """
Drop table If Exists SalesPerson
Create table If Not Exists SalesPerson (sales_id int, name varchar(255), salary int, commission_rate int, hire_date date)
insert into SalesPerson (sales_id, name, salary, commission_rate, hire_date) values ('1', 'John', '100000', '6', '4/1/2006')
insert into SalesPerson (sales_id, name, salary, commission_rate, hire_date) values ('2', 'Amy', '12000', '5', '5/1/2010')
insert into SalesPerson (sales_id, name, salary, commission_rate, hire_date) values ('3', 'Mark', '65000', '12', '12/25/2008')
insert into SalesPerson (sales_id, name, salary, commission_rate, hire_date) values ('4', 'Pam', '25000', '25', '1/1/2005')
insert into SalesPerson (sales_id, name, salary, commission_rate, hire_date) values ('5', 'Alex', '5000', '10', '2/3/2007')
Drop table If Exists Company
Create table If Not Exists Company (com_id int, name varchar(255), city varchar(255))
insert into Company (com_id, name, city) values ('1', 'RED', 'Boston')
insert into Company (com_id, name, city) values ('2', 'ORANGE', 'New York')
insert into Company (com_id, name, city) values ('3', 'YELLOW', 'Boston')
insert into Company (com_id, name, city) values ('4', 'GREEN', 'Austin')
Drop table If Exists Orders
Create table If Not Exists Orders (order_id int, order_date date, com_id int, sales_id int, amount int)
insert into Orders (order_id, order_date, com_id, sales_id, amount) values ('1', '1/1/2014', '3', '4', '10000')
insert into Orders (order_id, order_date, com_id, sales_id, amount) values ('2', '2/1/2014', '4', '5', '5000')
insert into Orders (order_id, order_date, com_id, sales_id, amount) values ('3', '3/1/2014', '1', '1', '50000')
insert into Orders (order_id, order_date, com_id, sales_id, amount) values ('4', '4/1/2014', '1', '4', '25000')
"""
execute_formatted_sqlite(sql_schema)

In [52]:
sql = """--sql
SELECT
    s.name
FROM
    SalesPerson s
WHERE
    NOT EXISTS (
        SELECT
            1
        FROM
            Orders o
            INNER JOIN Company c ON o.com_id = c.com_id
        WHERE
            c.name = 'RED'
            AND o.sales_id = s.sales_id
    )
ORDER BY
    s.name;
"""
select(sql)

   name
0  Alex
1   Amy
2  Mark

### 608. Tree Node (Med.)

Each node in the tree can be one of three types:

- "Leaf": if the node is a leaf node.
- "Root": if the node is the root of the tree.
- "Inner": If the node is neither a leaf node nor a root node.

Write a solution to report the type of each node in the tree.

In [53]:
sql_schema = """
Drop table If Exists Tree
Create table If Not Exists Tree (id int, p_id int)
insert into Tree (id, p_id) values ('1', NULL)
insert into Tree (id, p_id) values ('2', '1')
insert into Tree (id, p_id) values ('3', '1')
insert into Tree (id, p_id) values ('4', '2')
insert into Tree (id, p_id) values ('5', '2')
"""
execute_formatted_sqlite(sql_schema)

In [54]:
sql = """--sql
SELECT
    t.id,
    CASE
        WHEN t.p_id IS NULL THEN 'Root'
        WHEN EXISTS (
            SELECT
                1
            FROM
                Tree
            WHERE
                t.id = Tree.p_id
        ) THEN 'Inner'
        ELSE 'Leaf'
    END AS type
FROM
    Tree t;
"""
select(sql)

   id   type
0   1   Root
1   2  Inner
2   3   Leaf
3   4   Leaf
4   5   Leaf

### 610. Triangle Judgement (Easy)

Report for every three line segments whether they can form a triangle.

In [55]:
sql_schema = """
Drop table If Exists Triangle
Create table If Not Exists Triangle (x int, y int, z int)
insert into Triangle (x, y, z) values ('13', '15', '30')
insert into Triangle (x, y, z) values ('10', '20', '15')
"""
execute_formatted_sqlite(sql_schema)

In [56]:
sql = """--sql
SELECT
    t.x,
    t.y,
    t.z,
    CASE
        WHEN t.x < t.y + t.z
        AND t.y < t.x + t.z
        AND t.z < t.x + t.y THEN 'Yes'
        ELSE 'No'
    END AS triangle
FROM
    Triangle t;
"""
select(sql)

    x   y   z triangle
0  13  15  30       No
1  10  20  15      Yes

### 619. Biggest Single Number (Easy)

A single number is a number that appeared only once in the MyNumbers table.

Find the largest single number. If there is no single number, report null.

In [57]:
sql_schema = """
Drop table If Exists MyNumbers
Create table If Not Exists MyNumbers (num int)
insert into MyNumbers (num) values ('8')
insert into MyNumbers (num) values ('8')
insert into MyNumbers (num) values ('3')
insert into MyNumbers (num) values ('3')
insert into MyNumbers (num) values ('1')
insert into MyNumbers (num) values ('4')
insert into MyNumbers (num) values ('5')
insert into MyNumbers (num) values ('6')
"""
execute_formatted_sqlite(sql_schema)

In [58]:
# Тут нужно все же использовать подзапрос с агрегатной функцией, чтобы в случае отсутствия уникальных
# значений вернулось именно NULL, т.к. если просто выбрать строки, например через DESC и LIMIT 1, то и
# вернется пустая строка, а не значение NULL, как задано в условии.
sql = """--sql
SELECT
    MAX(m.num) AS num
FROM
    (
        SELECT
            n.num
        FROM
            MyNumbers n
        GROUP BY
            n.num
        HAVING
            COUNT(*) = 1
    ) m;
"""
select(sql)

   num
0    6

### 620. Not Boring Movies (Easy)

Write a solution to report the movies with an odd-numbered ID and a description that is not "boring".

Return the result table ordered by rating in descending order.

In [59]:
sql_schema = """
Drop table If Exists cinema
Create table If Not Exists cinema (id int, movie varchar(255), description varchar(255), rating float(2, 1))
insert into cinema (id, movie, description, rating) values ('1', 'War', 'great 3D', '8.9')
insert into cinema (id, movie, description, rating) values ('2', 'Science', 'fiction', '8.5')
insert into cinema (id, movie, description, rating) values ('3', 'irish', 'boring', '6.2')
insert into cinema (id, movie, description, rating) values ('4', 'Ice song', 'Fantacy', '8.6')
insert into cinema (id, movie, description, rating) values ('5', 'House card', 'Interesting', '9.1')
"""
execute_formatted_sqlite(sql_schema)

In [60]:
sql = """--sql
SELECT
    c.*
FROM
    cinema c
WHERE
    c.id % 2 != 0
    AND c.description != 'boring'
ORDER BY
    c.rating DESC;
"""
select(sql)

   id       movie  description  rating
0   5  House card  Interesting     9.1
1   1         War     great 3D     8.9

### 626. Exchange Seats (Med.)

Write a solution to swap the seat id of every two consecutive students. If the number of students is odd, the id of the last student is not swapped.

Return the result table ordered by id in ascending order.

In [61]:
sql_schema = """
Drop table If Exists Seat
Create table If Not Exists Seat (id int, student varchar(255))
insert into Seat (id, student) values ('1', 'Abbot')
insert into Seat (id, student) values ('2', 'Doris')
insert into Seat (id, student) values ('3', 'Emerson')
insert into Seat (id, student) values ('4', 'Green')
insert into Seat (id, student) values ('5', 'Jeames')
"""
execute_formatted_sqlite(sql_schema)

In [62]:
# В CASE нужно использовать именно подзапрос для MAX(id), чтобы вытянуть именно максимальное значение
# из таблицы и по нему сравнивать. Т.к. если AND s.id != MAX(s.id), то без группировки агрегатная функция
# свернет результат всего блока CASE в одну строку и запрос вернет одну эту строку с максимальным id.
sql = """--sql
SELECT
    CASE
        WHEN s.id % 2 = 1
        AND s.id != (
            SELECT
                MAX(id)
            FROM
                Seat
        ) THEN s.id + 1
        WHEN s.id % 2 = 0 THEN s.id - 1
        ELSE s.id
    END AS id,
    s.student
FROM
    Seat s
ORDER BY
    id;
"""
select(sql)

   id  student
0   1    Doris
1   2    Abbot
2   3    Green
3   4  Emerson
4   5   Jeames

### 627. Swap Salary (Easy)

Write a solution to swap all 'f' and 'm' values (i.e., change all 'f' values to 'm' and vice versa) with a single update statement and no intermediate temporary tables.

Note that you must write a single update statement, do not write any select statement for this problem.

In [63]:
sql_schema = """
Drop table If Exists Salary
Create table If Not Exists Salary (id int, name varchar(100), sex char(1), salary int)
insert into Salary (id, name, sex, salary) values ('1', 'A', 'm', '2500')
insert into Salary (id, name, sex, salary) values ('2', 'B', 'f', '1500')
insert into Salary (id, name, sex, salary) values ('3', 'C', 'm', '5500')
insert into Salary (id, name, sex, salary) values ('4', 'D', 'f', '500')
"""
execute_formatted_sqlite(sql_schema)

In [64]:
sql = """--sql
UPDATE Salary
SET sex = CASE
            WHEN sex = 'f' THEN 'm'
            ELSE 'f'
          END;
"""
crud(sql)

### 1045. Customers Who Bought All Products (Med.)

Write a solution to report the customer ids from the Customer table that bought all the products in the Product table.

In [65]:
sql_schema = """
Drop table If Exists Customer
Create table If Not Exists Customer (customer_id int, product_key int)
insert into Customer (customer_id, product_key) values ('1', '5')
insert into Customer (customer_id, product_key) values ('2', '6')
insert into Customer (customer_id, product_key) values ('3', '5')
insert into Customer (customer_id, product_key) values ('3', '6')
insert into Customer (customer_id, product_key) values ('1', '6')
Drop table If Exists Product
Create table Product (product_key int)
insert into Product (product_key) values ('5')
insert into Product (product_key) values ('6')
"""
execute_formatted_sqlite(sql_schema)

In [66]:
sql = """--sql
SELECT
    c.customer_id
FROM
    Customer c
GROUP BY
    c.customer_id
HAVING
    COUNT(DISTINCT c.product_key) = (
        SELECT
            COUNT(*)
        FROM
            Product
    );
"""
select(sql)

   customer_id
0            1
1            3

### 1050. Actors and Directors Who Cooperated At Least Three Times (Easy)

Write a solution to find all the pairs (actor_id, director_id) where the actor has cooperated with the director at least three times.

In [67]:
sql_schema = """
Drop table If Exists ActorDirector
Create table If Not Exists ActorDirector (actor_id int, director_id int, timestamp int)
insert into ActorDirector (actor_id, director_id, timestamp) values ('1', '1', '0')
insert into ActorDirector (actor_id, director_id, timestamp) values ('1', '1', '1')
insert into ActorDirector (actor_id, director_id, timestamp) values ('1', '1', '2')
insert into ActorDirector (actor_id, director_id, timestamp) values ('1', '2', '3')
insert into ActorDirector (actor_id, director_id, timestamp) values ('1', '2', '4')
insert into ActorDirector (actor_id, director_id, timestamp) values ('2', '1', '5')
insert into ActorDirector (actor_id, director_id, timestamp) values ('2', '1', '6')
"""
execute_formatted_sqlite(sql_schema)

In [ ]:
sql = """--sql
SELECT
    ad.actor_id,
    ad.director_id
FROM
    ActorDirector ad
GROUP BY
    ad.actor_id,
    ad.director_id
HAVING
    COUNT(*) >= 3;
"""
select(sql)

   actor_id  director_id
0         1            1

### 1068. Product Sales Analysis I (Easy)

Write a solution to report the product_name, year, and price for each sale_id in the Sales table.

In [69]:
sql_schema = """
Drop table If Exists Sales
Create table If Not Exists Sales (sale_id int, product_id int, year int, quantity int, price int)
insert into Sales (sale_id, product_id, year, quantity, price) values ('1', '100', '2008', '10', '5000')
insert into Sales (sale_id, product_id, year, quantity, price) values ('2', '100', '2009', '12', '5000')
insert into Sales (sale_id, product_id, year, quantity, price) values ('7', '200', '2011', '15', '9000')
Drop table If Exists Product
Create table If Not Exists Product (product_id int, product_name varchar(10))
insert into Product (product_id, product_name) values ('100', 'Nokia')
insert into Product (product_id, product_name) values ('200', 'Apple')
insert into Product (product_id, product_name) values ('300', 'Samsung')
"""
execute_formatted_sqlite(sql_schema)

In [ ]:
sql = """--sql

"""
select(sql)